### ISSUE TITLE
Walking back L1Block by hash

### ISSUE THREAD

**Issue by sahfd4eiugf** [blast-io/deployment#12]
Sometimes when you loose sync, and do a clean shutdown and re-start, the node is stuck walking back L1 blocks for hours until you just give up, clear the cache and redo the whole sync from genesis. Frustrating it is.

**Comment by dolphintwo** [comment]
same here

```log
DEBUG[05-28|02:32:41.849] Couldn't get external IP                 err="no UPnP or NAT-PMP router discovered" interface="UPnP or NAT-PMP"
DEBUG[05-28|02:32:41.850] Couldn't add port mapping                proto=TCP extport=30303 intport=30303 interface="UPnP or NAT-PMP" err="no UPnP or NAT-PMP router discovered"
```

**Comment by sahfd4eiugf** [comment]
Yup and a "full snap" sync on Blast takes 4-5 days each time, for a 3 months old block chain. I just re-synced my ETH full node on snap, and it was done in 3-4 hours.
