### ISSUE TITLE
How big is the node size of the mainnet data now?

### ISSUE THREAD

**Issue by bijianing97** [blast-io/deployment#13]
What is the node size of the main network now? As of UTC 2024-05-27, is it normal to be about 810G?

**Comment by dolphintwo** [comment]
812G	blast-geth-data/geth/chaindata/

**Comment by bijianing97** [comment]
> 812G blast-geth-data/geth/chaindata/

lol,the blast data is growing really fast

**Comment by sahfd4eiugf** [comment]
You will know for sure because whether you try to sync a snap (full) Blast node or an archive, it will start from genesis anyway and scan every single block :D
